import torch
import numpy
a = numpy.array([[1,2],[3,4]])
# print('numpy:')
# print('.dot:')
# print(a.dot(a))
# print('.matmul:')
# print(numpy.matmul(a,a))
# print('*')
# print(a*a)
# print('torch:')
b = torch.randn((2,4))
c = torch.randn((2,))
# print(b)
# print('dot:')
# print(b.mul(b))
# print('mm:')
# print(b.mm(b))
print(b)
print(c)
print(b+c)
